"""Tests for catchup/write_guide.py — the GUIDE.md assembler.

Phase 3 of `/catchup` used to be pure prose: the agent hand-derived the date
stamp, hand-decided which sections to omit, and hand-reported the line count,
while nothing checked that a `{placeholder}` had not survived. These tests pin
the mechanics the script now owns, the Writer Safety Contract for the tracked
root `GUIDE.md`, and the boundary it must not cross — it never generates
narrative.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path
from types import ModuleType

import pytest

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / ".agents" / "skills" / "catchup" / "write_guide.py"
VALIDATE_DOC = REPO_ROOT / ".agents" / "skills" / "_shared" / "validate_doc.py"

NOW = "2026-07-25T09:30:00+00:00"

BODY = {
    "what_is_this_project": "- **Purpose**: Shared agent contract.",
    "recent_work": "- Wave 1 shared writers (12 commits)",
    "capabilities": "### Slash commands\n\n| Command | Purpose |\n|---|---|\n| /catchup | onboarding |",
    "resume_work": "- **Environment setup**: `uv sync`",
}


def _load_module(path: Path, name: str) -> ModuleType:
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


wg = _load_module(SCRIPT, "write_guide_under_test")


@pytest.fixture
def project(tmp_path: Path) -> Path:
    (tmp_path / ".agents" / "logs").mkdir(parents=True)
    return tmp_path


def write_input(project: Path, data: dict) -> Path:
    path = project / "body.json"
    path.write_text(json.dumps(data, ensure_ascii=False), encoding="utf-8")
    return path


def run(project: Path, data: dict, *extra: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--project-root",
            str(project),
            "--input",
            str(write_input(project, data)),
            "--now",
            NOW,
            *extra,
        ],
        capture_output=True,
        text=True,
        check=False,
    )


def parsed(result: subprocess.CompletedProcess[str]) -> dict:
    return json.loads(result.stdout)


# --- dry-run by default ------------------------------------------------------


def test_dry_run_writes_only_a_preview(project: Path) -> None:
    result = run(project, BODY)

    assert result.returncode == 0, result.stdout
    payload = parsed(result)
    assert payload["result"] == "preview"
    assert payload["applied"] is False
    assert payload["preview_path"] == ".agents/logs/guide-preview-20260725-093000.md"
    assert not (project / "GUIDE.md").exists()
    assert payload["artifacts"] == [payload["preview_path"]]


def test_the_preview_is_byte_identical_to_what_apply_writes(project: Path) -> None:
    run(project, BODY)
    preview = (
        project / ".agents" / "logs" / "guide-preview-20260725-093000.md"
    ).read_text(encoding="utf-8")

    run(project, BODY, "--apply")

    assert (project / "GUIDE.md").read_text(encoding="utf-8") == preview


# --- stamping, ordering, numbering ------------------------------------------


def test_the_date_comes_from_the_injected_clock(project: Path) -> None:
    run(project, BODY, "--apply")

    text = (project / "GUIDE.md").read_text(encoding="utf-8")
    assert "_Generated by `/catchup` on 2026-07-25_" in text
    assert text.startswith("# Project Guide\n")


def test_omitting_optional_sections_never_renumbers_the_rest(project: Path) -> None:
    """The numbers are part of the names validate_doc.py's `guide` contract
    requires, so renumbering would break the contract on every partial guide."""
    result = run(project, BODY, "--apply")

    payload = parsed(result)
    assert payload["sections_written"] == [
        "what_is_this_project",
        "recent_work",
        "capabilities",
        "resume_work",
    ]
    assert payload["sections_omitted"] == [
        "current_state",
        "architecture",
        "project_rules",
        "recent_sessions",
    ]
    headings = [
        line
        for line in (project / "GUIDE.md").read_text(encoding="utf-8").splitlines()
        if line.startswith("## ")
    ]
    assert headings == [
        "## 1. What is this project?",
        "## 3. Recent Work (last 30 days)",
        "## 5. Capabilities",
        "## 7. How to Resume Work",
    ]


def test_sections_are_emitted_in_template_order(project: Path) -> None:
    scrambled = {
        "recent_sessions": "- checkpoint 1",
        "resume_work": BODY["resume_work"],
        "capabilities": BODY["capabilities"],
        "current_state": "- **Active branch**: main",
        "recent_work": BODY["recent_work"],
        "what_is_this_project": BODY["what_is_this_project"],
    }

    run(project, scrambled, "--apply")

    text = (project / "GUIDE.md").read_text(encoding="utf-8")
    numbers = [
        line.split(".")[0].removeprefix("## ")
        for line in text.splitlines()
        if line.startswith("## ")
    ]
    assert numbers == ["1", "2", "3", "5", "7", "8"]


def test_the_result_satisfies_the_shared_guide_contract(project: Path) -> None:
    run(project, BODY, "--apply")

    result = subprocess.run(
        [
            sys.executable,
            str(VALIDATE_DOC),
            "--contract",
            "guide",
            "--file",
            str(project / "GUIDE.md"),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, result.stdout


def test_line_count_matches_the_written_file(project: Path) -> None:
    payload = parsed(run(project, BODY, "--apply"))

    text = (project / "GUIDE.md").read_text(encoding="utf-8")
    assert payload["line_count"] == len(text.splitlines())


# --- refusals ----------------------------------------------------------------


def test_a_residual_placeholder_is_rejected(project: Path) -> None:
    body = {**BODY, "current_state": "- **Active branch**: {branch name}"}

    result = run(project, body)

    assert result.returncode == 2, result.stdout
    payload = parsed(result)
    assert payload["residual_placeholders"] == ["{branch name}"]
    assert not (project / "GUIDE.md").exists()


def test_braces_inside_a_fenced_code_block_are_not_placeholders(
    project: Path,
) -> None:
    body = {
        **BODY,
        "resume_work": "```bash\nuv run python -c 'print({\"a\": 1})'\n```",
    }

    result = run(project, body, "--apply")

    assert result.returncode == 0, result.stdout
    assert parsed(result)["residual_placeholders"] == []


def test_an_unknown_section_id_is_rejected(project: Path) -> None:
    result = run(project, {**BODY, "chapter_nine": "..."})

    assert result.returncode == 2, result.stdout
    assert "unknown section id(s): chapter_nine" in parsed(result)["error"]


def test_a_missing_required_section_is_rejected(project: Path) -> None:
    body = {key: value for key, value in BODY.items() if key != "capabilities"}

    result = run(project, body)

    assert result.returncode == 2, result.stdout
    assert "capabilities" in parsed(result)["error"]


def test_an_empty_required_section_counts_as_missing(project: Path) -> None:
    result = run(project, {**BODY, "recent_work": "   \n"})

    assert result.returncode == 2, result.stdout
    assert "recent_work" in parsed(result)["error"]


def test_a_non_string_body_is_bad_input(project: Path) -> None:
    result = run(project, {**BODY, "current_state": ["a", "b"]})

    assert result.returncode == 1, result.stdout
    assert parsed(result)["ok"] is False


def test_unreadable_input_is_bad_input(project: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--project-root",
            str(project),
            "--input",
            str(project / "nope.json"),
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 1
    assert parsed(result)["ok"] is False


def test_an_unparseable_now_is_bad_input(project: Path) -> None:
    result = subprocess.run(
        [
            sys.executable,
            str(SCRIPT),
            "--project-root",
            str(project),
            "--input",
            str(write_input(project, BODY)),
            "--now",
            "tomorrow",
        ],
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 1
    assert "--now" in parsed(result)["error"]


def test_the_script_never_generates_narrative() -> None:
    """The boundary: no section body may be synthesised from collected data."""
    source = SCRIPT.read_text(encoding="utf-8")
    assert "--input" in source
    for forbidden in ('["git"', "collect_repo_state", "def generate_"):
        assert forbidden not in source, f"{forbidden!r} crosses the prose boundary"
    # Every section body originates in --input: compose_guide reads only *data*.
    compose = source[
        source.index("def compose_guide") : source.index("def validate_guide")
    ]
    assert "data.get(section.key)" in compose
    assert "root" not in compose and "read_text" not in compose


# --- Writer Safety -----------------------------------------------------------


def test_the_hash_guard_refuses_a_guide_changed_since_load(
    project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    guide = project / "GUIDE.md"
    guide.write_text("# Project Guide\n\nold\n", encoding="utf-8")
    real_read_text = Path.read_text
    real_write_text = Path.write_text
    reads = {"n": 0}

    def counting_read_text(self: Path, *args: object, **kwargs: object) -> str:
        if self.name == "GUIDE.md":
            reads["n"] += 1
            if reads["n"] == 1:
                text = real_read_text(self, *args, **kwargs)  # type: ignore[arg-type]
                real_write_text(self, text + "\nconcurrent note\n")  # type: ignore[arg-type]
                return text
        return real_read_text(self, *args, **kwargs)  # type: ignore[arg-type,return-value]

    monkeypatch.setattr(Path, "read_text", counting_read_text)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "write_guide.py",
            "--project-root",
            str(project),
            "--input",
            str(write_input(project, BODY)),
            "--apply",
        ],
    )

    assert wg.main() == 3
    text = real_read_text(guide)  # type: ignore[arg-type]
    assert "concurrent note" in text, "the concurrent write must survive"
    assert "Shared agent contract" not in text, "our write must not have landed"


def test_validation_runs_before_the_replace_and_leaves_no_temp_file(
    project: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    guide = project / "GUIDE.md"
    guide.write_text("# Project Guide\n\nold\n", encoding="utf-8")
    calls = {"n": 0}

    def failing_second_validation(text: str, project_root: Path) -> str | None:
        calls["n"] += 1
        return "injected structural damage" if calls["n"] == 2 else None

    monkeypatch.setattr(wg, "validate_guide_document", failing_second_validation)
    monkeypatch.setattr(
        sys,
        "argv",
        [
            "write_guide.py",
            "--project-root",
            str(project),
            "--input",
            str(write_input(project, BODY)),
            "--apply",
        ],
    )

    assert wg.main() == 2
    assert guide.read_text(encoding="utf-8") == "# Project Guide\n\nold\n"
    assert list(project.glob(".GUIDE.md-*")) == []


def test_help_exits_zero_and_documents_the_flags() -> None:
    result = subprocess.run(
        [sys.executable, str(SCRIPT), "--help"], capture_output=True, text=True
    )
    assert result.returncode == 0
    for flag in ("--input", "--apply", "--now", "--project-root"):
        assert flag in result.stdout
