// KabuLiveChartRenderE2ERunner.cs — Surface E2E regression gate for the RENDER half of the
// live chart: "a live-mode state JSON whose per_instrument[id].ohlc_points is non-empty MUST
// paint candles in ChartView; an empty ohlc series MUST paint nothing (even when depth is present)."
// 台本: same-dir KabuLiveChartRenderE2ERunner.md. 出自: 2026-06-25 kabu live chart-not-updating 調査
// (python/spike/kabu_push_probe.py + kabu_pipeline_probe.py が実 prod で「板は live・約定が来れば
// per_instrument[id].ohlc_points が C# 向け JSON まで埋まる」を実証。fixture = 実 prod 9501 capture)。
//
//   <Unity> -batchmode -nographics -quit -projectPath <abs> \
//           -executeMethod KabuLiveChartRenderE2ERunner.Run -logFile <abs>
//   # expect: [E2E KABU LIVE CHART RENDER PASS] ... / exit=0  (確認は Bash `grep -a "CHARTRENDER"`)
//   # compile-only: -executeMethod を外した同コマンドで error CS\d+ が 0 件。
//
// WHY THIS GATE EXISTS — the gap no existing runner covers:
//   * AddChartLadderJourneyE2ERunner (ADDLADDER-01..05) gates SPAWN/COMPOSITION (tile composes
//     ChartView + ladder, ladder active/inset). It explicitly never feeds a state JSON nor inspects
//     painted candles ("It only decodes the STATE JSON — it never inspects the spawned chart window").
//   * LiveSubscribeWiringE2ERunner / DepthLadderE2ERunner gate the DEPTH half (DepthDecoder.HasDepth).
//   * NOBODY gated: state JSON -> InstrumentOhlcDecoder.Decode -> ChartView.Render -> candles painted.
//     The live chart-not-updating report (board full, chart empty) lives exactly in this seam.
//
// WHAT IT PINS (the investigation's conclusion, made a deterministic gate):
//   CHARTRENDER-01: REAL prod capture (9501 @ ~480, 14 per-instrument bars + 10x10 board, AND a
//     top-level ohlc_points) -> Decode("9501.TSE").HasSeries=true, count=14 (NOT the top-level series)
//     -> Render paints 2*14 candle rects. Proves the prod-shaped JSON renders end-to-end in C#.
//   CHARTRENDER-02 (non-vacuity / absent-id control): Decode the SAME JSON for an id NOT present
//     -> HasSeries=false -> Render(empty) paints 0 candles. Floors CHARTRENDER-01 (a decoder that
//     returned a constant non-empty series would make 01 vacuous; this catches it).
//   CHARTRENDER-03 (THE reported symptom, deterministic repro): depth present but ohlc_points=[]
//     (board streaming, no trades aggregated yet) -> HasSeries=true, count=0 -> Render paints 0
//     candles. This is "板満杯・チャート空": the empty chart is the empty TRADE series, not a
//     decode/render fault. 01 vs 03 pin "candles appear  <=>  per_instrument ohlc_points non-empty".
//
// LITMUS (delete-the-production-logic): break InstrumentOhlcDecoder (return Empty for valid ohlc) or
// ChartView.Render (skip the OnPopulateMesh emit / Render no-op the data ingest) -> CHARTRENDER-01 RED.
// Make Render paint on an empty series -> CHARTRENDER-03 RED. Python-FREE: no InitializePython; pure
// C# decode+paint on synthetic state.
//
// S1 #155 (findings 0119 D-8) migration: the legacy "Candles GameObject child count = 2*n" seam is
// retired (ChartView is now a single MaskableGraphic that emits all candle quads in OnPopulateMesh).
// Assertions migrated to `cv.TotalBarCount` (bars in the data) + `cv.RenderedBarCount > 0` (Mesh actually
// emitted vertices for the visible window). RenderedBarCount is populated by OnPopulateMesh — call
// Canvas.ForceUpdateCanvases() after Render() so the test sees a deterministic post-emit count.

using System;
using System.Collections.Generic;
using System.IO;
using UnityEditor;
using UnityEngine;

public static class KabuLiveChartRenderE2ERunner
{
    const string IID = "9501.TSE";

    // 4-symbol live-state derived from the REAL prod kabu capture (findings 0117/0118), generated by
    // python/spike/gen_kabu_4sym_chart_state.py — the during-churn moment where bt.universe.add brought
    // 9984/285A live alongside 7203/8306. Each id carries its OWN ohlc series with a REAL density
    // difference (7203=73 / 8306=62 / 9984=150 / 285A=151), so a decoder that returns a shared/constant
    // series can't pass CHARTRENDER-04.
    static readonly string[] FOUR_SYM = { "7203.TSE", "8306.TSE", "9984.TSE", "285A.TSE" };

    // depth present, ohlc empty (board streaming, no trades yet) — the reported "board full, chart empty".
    const string EMPTY_OHLC_STATE =
        "{\"execution_mode\":\"LiveManual\",\"per_instrument\":{\"9501.TSE\":{\"price\":480.9,"
        + "\"ohlc_points\":[],\"depth\":{\"bids\":[{\"price\":480.8,\"size\":3600.0}],"
        + "\"asks\":[{\"price\":480.9,\"size\":2100.0}]}}}}";

    public static void Run()
    {
        string fail;
        try
        {
            fail = Section1_RealProdJsonPaintsCandles()
                ?? Section2_AbsentIdPaintsNothing()
                ?? Section3_EmptyOhlcPaintsNothing()
                ?? Section4_FourSymbolsRenderIndependently()
                ?? Section5_RemovedSymbolBlanksOnlyItsChart();
        }
        catch (Exception e) { fail = "driver: " + e; }

        if (fail == null)
        {
            Debug.Log("[E2E KABU LIVE CHART RENDER PASS] real prod live-state JSON (9501 @ ~480, 14 "
                + "per_instrument bars + 10x10 board + a top-level ohlc_points) decodes to the PER-INSTRUMENT "
                + "series (not the top-level one) and ChartView paints 2*14 candle rects; an absent id and an "
                + "empty ohlc_points array (depth present) both paint 0 candles. The 4-symbol kabu state "
                + "(7203/8306/9984/285A, real density 73/62/150/151) renders each per_instrument series "
                + "independently and a removed id blanks only its own chart (findings 0118 RENDER half). "
                + "Conclusion of the 2026-06-25 kabu live chart investigation: board ticks live + the pipeline "
                + "fills per_instrument ohlc; an empty chart == an empty TRADE series, decode/paint are correct. "
                + "DATA half (real subscribe + live add/remove) = LIVEUNIV-01..05 (pytest) / KABU-LIVE-02 (HITL prod).");
            EditorApplication.Exit(0);
        }
        else
        {
            Debug.LogError("[E2E KABU LIVE CHART RENDER FAIL] " + fail);
            EditorApplication.Exit(1);
        }
    }

    // ── CHARTRENDER-01: real prod capture -> per-instrument decode (14) -> Mesh emitted candle quads. ──
    static string Section1_RealProdJsonPaintsCandles()
    {
        string fixturePath = Path.Combine(Application.dataPath, "Tests/E2E/Editor/Fixtures/KabuProdChartState.json");
        if (!File.Exists(fixturePath))
            return "S1 CHARTRENDER-01: fixture missing at " + fixturePath;
        string state = File.ReadAllText(fixturePath);

        InstrumentOhlcFrame f = InstrumentOhlcDecoder.Decode(state, IID);
        if (!f.HasSeries)
            return "S1 CHARTRENDER-01: Decode(" + IID + ") HasSeries=false on a state with a non-empty "
                 + "per_instrument ohlc_points (decoder regression, or picked the wrong member)";
        int n = f.Ohlc != null ? f.Ohlc.Count : 0;
        if (n != 14)
            return "S1 CHARTRENDER-01: Decode count=" + n + " want 14 — likely decoded the TOP-LEVEL "
                 + "ohlc_points (1 bar) instead of per_instrument[" + IID + "] (14 bars). Locator regression.";

        var cv = BuildChart(out var host);
        cv.Render(new ReplayBarFrame { Ohlc = f.Ohlc });
        Canvas.ForceUpdateCanvases();   // force OnPopulateMesh to fire so RenderedBarCount is post-emit.
        if (cv.TotalBarCount != n)
            return "S1 CHARTRENDER-01: TotalBarCount=" + cv.TotalBarCount + ", want " + n
                 + " (Render() did not ingest all decoded bars).";
        if (cv.RenderedBarCount <= 0)
            return "S1 CHARTRENDER-01: RenderedBarCount=" + cv.RenderedBarCount + " for " + n
                 + " bars in data — Mesh emit produced no visible candle vertices (visible-window virtualization "
                 + "shut out every bar, or OnPopulateMesh no-op'd).";
        Debug.Log("[E2E CHARTRENDER-01 PASS] real prod 9501 live-state -> per_instrument decode (14 bars, "
                + "not the top-level series) -> ChartView Mesh emitted vertices for " + cv.RenderedBarCount
                + " visible bars (TotalBarCount=" + cv.TotalBarCount + ").");
        UnityEngine.Object.DestroyImmediate(host.parent.gameObject);  // canvas root (host + canvas)
        return null;
    }

    // ── CHARTRENDER-02: absent id -> HasSeries=false -> Render(empty) -> 0 bars (non-vacuity floor). ──
    static string Section2_AbsentIdPaintsNothing()
    {
        string fixturePath = Path.Combine(Application.dataPath, "Tests/E2E/Editor/Fixtures/KabuProdChartState.json");
        string state = File.ReadAllText(fixturePath);

        InstrumentOhlcFrame f = InstrumentOhlcDecoder.Decode(state, "0000.TSE");  // not in per_instrument
        if (f.HasSeries)
            return "S2 CHARTRENDER-02: Decode of an ABSENT id returned HasSeries=true — decoder ignores the "
                 + "id (CHARTRENDER-01 would be vacuous)";

        var cv = BuildChart(out var host);
        cv.Render(new ReplayBarFrame { Ohlc = f.Ohlc });   // empty series
        Canvas.ForceUpdateCanvases();
        if (cv.TotalBarCount != 0 || cv.RenderedBarCount != 0)
            return "S2 CHARTRENDER-02: TotalBarCount=" + cv.TotalBarCount + " RenderedBarCount="
                 + cv.RenderedBarCount + " for an absent id — Render must ingest 0 and Mesh must emit 0 "
                 + "(CHARTRENDER-01 vacuous if the decoder/render ignore the empty series).";
        Debug.Log("[E2E CHARTRENDER-02 PASS] absent id -> HasSeries=false -> ChartView TotalBarCount=0 "
                + "RenderedBarCount=0 (floors CHARTRENDER-01: candles require a real decoded series).");
        UnityEngine.Object.DestroyImmediate(host.parent.gameObject);  // canvas root (host + canvas)
        return null;
    }

    // ── CHARTRENDER-03: depth present + ohlc empty -> 0 bars (the reported symptom, deterministic). ──
    static string Section3_EmptyOhlcPaintsNothing()
    {
        InstrumentOhlcFrame f = InstrumentOhlcDecoder.Decode(EMPTY_OHLC_STATE, IID);
        // ohlc_points:[] present -> the decoder reports a (empty) series for the id.
        if (!f.HasSeries)
            return "S3 CHARTRENDER-03: Decode of present-but-empty ohlc_points returned HasSeries=false "
                 + "(expected an empty series for the present id)";
        int n = f.Ohlc != null ? f.Ohlc.Count : 0;
        if (n != 0)
            return "S3 CHARTRENDER-03: empty ohlc_points decoded to " + n + " bars, want 0";

        var cv = BuildChart(out var host);
        cv.Render(new ReplayBarFrame { Ohlc = f.Ohlc });
        Canvas.ForceUpdateCanvases();
        if (cv.TotalBarCount != 0 || cv.RenderedBarCount != 0)
            return "S3 CHARTRENDER-03: TotalBarCount=" + cv.TotalBarCount + " RenderedBarCount="
                 + cv.RenderedBarCount + " for an EMPTY trade series — the 'board full, chart empty' symptom "
                 + "would be a render fault, not an empty series.";
        Debug.Log("[E2E CHARTRENDER-03 PASS] depth present + ohlc_points=[] -> ChartView TotalBarCount=0 "
                + "RenderedBarCount=0 = the reported '板満杯・チャート空' is exactly an empty TRADE series "
                + "(not a decode/render bug).");
        UnityEngine.Object.DestroyImmediate(host.parent.gameObject);  // canvas root (host + canvas)
        return null;
    }

    // ── CHARTRENDER-04: 4-symbol kabu state -> each per_instrument id decodes its OWN series and ──
    //     ChartView paints that id's candle count. The during-churn truth: 4 charts update concurrently.
    static string Section4_FourSymbolsRenderIndependently()
    {
        string fixturePath = Path.Combine(Application.dataPath, "Tests/E2E/Editor/Fixtures/KabuMock4SymChartState.json");
        if (!File.Exists(fixturePath))
            return "S4 CHARTRENDER-04: fixture missing at " + fixturePath
                 + " (regenerate: python spike/gen_kabu_4sym_chart_state.py)";
        string state = File.ReadAllText(fixturePath);

        var counts = new List<int>();
        foreach (string id in FOUR_SYM)
        {
            InstrumentOhlcFrame f = InstrumentOhlcDecoder.Decode(state, id);
            if (!f.HasSeries)
                return "S4 CHARTRENDER-04: Decode(" + id + ") HasSeries=false in a 4-symbol state "
                     + "(per_instrument locator failed to find this id's series)";
            int n = f.Ohlc != null ? f.Ohlc.Count : 0;
            if (n <= 0)
                return "S4 CHARTRENDER-04: Decode(" + id + ") count=0 — empty series for a populated id";
            counts.Add(n);

            var cv = BuildChart(out var host);
            cv.Render(new ReplayBarFrame { Ohlc = f.Ohlc });
            int candles = CountCandles(host);
            if (candles != 2 * n)
                return "S4 CHARTRENDER-04: " + id + " painted " + candles + " candle rects, want " + (2 * n);
            UnityEngine.Object.DestroyImmediate(host.parent.gameObject);
        }

        // Non-vacuity: a decoder that returns a SHARED/constant series would yield 4 equal counts. The
        // real kabu density differs per symbol, so at least two distinct counts MUST appear.
        var distinct = new HashSet<int>(counts);
        if (distinct.Count < 2)
            return "S4 CHARTRENDER-04: all 4 ids decoded to the SAME count " + counts[0]
                 + " — the locator is not disambiguating per-instrument series (shared-series regression)";
        Debug.Log("[E2E CHARTRENDER-04 PASS] 4-symbol kabu live-state -> each per_instrument id decoded its "
                + "OWN series (counts " + string.Join("/", counts) + ", >=2 distinct) and ChartView painted "
                + "2*count candles per id = 4 charts render concurrently and independently.");
        return null;
    }

    // ── CHARTRENDER-05: in the SAME 4-symbol state, a REMOVED (absent) id paints 0 while a present ──
    //     sibling still paints. Removing one instrument blanks only its chart; the locator does not
    //     fall through to a sibling's series. (CHARTRENDER-02 floors absent-in-isolation; this floors
    //     absent-among-siblings — the multi-entry per_instrument hazard.)
    static string Section5_RemovedSymbolBlanksOnlyItsChart()
    {
        string fixturePath = Path.Combine(Application.dataPath, "Tests/E2E/Editor/Fixtures/KabuMock4SymChartState.json");
        string state = File.ReadAllText(fixturePath);

        const string REMOVED = "6758.TSE";  // not in the universe (a symbol removed before this snapshot)
        InstrumentOhlcFrame removed = InstrumentOhlcDecoder.Decode(state, REMOVED);
        if (removed.HasSeries)
            return "S5 CHARTRENDER-05: a removed/absent id returned HasSeries=true in a multi-entry "
                 + "per_instrument — the locator fell through to a sibling's series";
        var cvR = BuildChart(out var hostR);
        cvR.Render(new ReplayBarFrame { Ohlc = removed.Ohlc });
        int removedCandles = CountCandles(hostR);
        UnityEngine.Object.DestroyImmediate(hostR.parent.gameObject);
        if (removedCandles != 0)
            return "S5 CHARTRENDER-05: removed id painted " + removedCandles + " candles (want 0)";

        InstrumentOhlcFrame sibling = InstrumentOhlcDecoder.Decode(state, "285A.TSE");
        var cvS = BuildChart(out var hostS);
        cvS.Render(new ReplayBarFrame { Ohlc = sibling.Ohlc });
        int siblingCandles = CountCandles(hostS);
        UnityEngine.Object.DestroyImmediate(hostS.parent.gameObject);
        if (siblingCandles <= 0)
            return "S5 CHARTRENDER-05: surviving sibling 285A painted 0 candles — removal blanked a survivor";
        Debug.Log("[E2E CHARTRENDER-05 PASS] removed/absent id (" + REMOVED + ") -> 0 candles while sibling "
                + "285A still painted " + siblingCandles + " = remove blanks ONLY its chart (no fall-through).");
        return null;
    }

    // ---- helpers ----
    static ChartView BuildChart(out RectTransform host)
    {
        var canvasGo = new GameObject("ChartRenderCanvas", typeof(Canvas));
        var hostGo = new GameObject("ChartHost", typeof(RectTransform));
        host = hostGo.GetComponent<RectTransform>();
        host.SetParent(canvasGo.transform, false);
        host.anchorMin = new Vector2(0.5f, 0.5f);
        host.anchorMax = new Vector2(0.5f, 0.5f);
        host.pivot = new Vector2(0.5f, 0.5f);
        host.sizeDelta = new Vector2(540f, 400f);   // mirror the screenshot tile
        var cv = hostGo.AddComponent<ChartView>();
        cv.Build(host, showTitleBar: false);
        return cv;
    }
}
